baseURL = '/'
languageCode = 'en-us'
title = 'goup-util'
theme = 'hugo-book'

[params]
  BookToC = true
  BookSection = '/'
  BookRepo = 'https://github.com/joeblew999/goup-util'
  BookEditPath = 'edit/main/docs/content'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
